// src/infrastructure/database/repositories/DrizzleUserAdapter.ts

import { inject, injectable, singleton } from 'tsyringe'
import { type DbClient } from '../drizzle/client'
import { userRoles, users } from '../drizzle/schema'

import { IUserRepository } from '../../../domain/repositories/IUserRepository'
import { User } from '../../../domain/entities/User'
import { UserNotFoundError } from '../../../domain/errors/DomainError'
import { eq, sql } from 'drizzle-orm'
import { INJECTION_TOKENS } from '../../DI/InjectionTokens'
import { executeWithRetry, isSerializationError } from '../../../shared/utils/concurrency'
import { Config } from '../../config/env'

/**
 * @class DrizzleUserAdapter
 * @description Adaptador que implementa el contrato IUserRepository (Port)
 * utilizando Drizzle ORM y PostgreSQL (Adapter).
 * Es responsable de mapear Entidades de Dominio a DTOs de Drizzle y viceversa.
 * @author Petpay Architecture Team
 * @version 1.0
 */
@injectable()
@singleton()
export class DrizzleUserAdapter implements IUserRepository {
  private readonly db: DbClient

  /**
   * @constructor
   * @param {DbClient} db - Cliente Drizzle inyectado por el contenedor DI.
   */
  constructor (@inject(INJECTION_TOKENS.DB_CLIENT) db: DbClient) {
    this.db = db
  }

  // --- Mappers ---

  /**
   * @private
   * Mapea un resultado de consulta de Drizzle a la Entidad de Dominio User.
   */
  private mapToDomain (dbUser: typeof users.$inferSelect & { roles: string[] }): User {
    if (dbUser.id === '' || dbUser.id === null || dbUser.id === undefined) {
      throw new Error('User fetched from DB must have an ID')
    }

    // Convertir el ID de string (DB) a number (Entidad User, si se hubiera usado number)
    // Usamos el ID de tipo string (varchar(36)) tal como está definido en el esquema.

    return new User({
      id: dbUser.id,
      email: dbUser.email,
      passwordHash: dbUser.passwordHash,
      firstName: dbUser.firstName,
      lastName: dbUser.lastName,
      phone: dbUser.phone ?? undefined,
      roles: dbUser.roles as any, // Cast a Role[]
      isVerified: dbUser.isVerified,
      createdAt: dbUser.createdAt,
      updatedAt: dbUser.updatedAt
    })
  }

  // --- Implementación IUserRepository ---

  /**
   * {@inheritDoc}
   * Implementa la lógica de persistencia transaccional del Aggregate Root User.
   * * Importante: La lógica de creación de Account para un nuevo usuario ocurre aquí
   * * como parte del Aggregate Root o se delega a la capa de Aplicación.
   * * Usa SERIALIZABLE isolation level con retry logic para prevenir race conditions.
   */
  public async save (user: User): Promise<User> {
    const isNewUser = user.id === null || user.id === undefined || user.id === ''

    const retryConfig = {
      maxRetries: Config.CONCURRENCY_MAX_RETRIES,
      initialDelayMs: Config.CONCURRENCY_RETRY_DELAY_MS,
      maxDelayMs: 5000,
      backoffFactor: Config.CONCURRENCY_BACKOFF_FACTOR
    }

    return await executeWithRetry(
      async () => {
        return this.db.transaction(async (tx) => {
          // Set transaction isolation level to SERIALIZABLE
          await tx.execute(sql`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`)

          let savedUser: typeof users.$inferSelect

          // 1. Insertar o Actualizar la tabla principal de usuarios
          if (isNewUser) {
            // Generamos el ID si es un nuevo usuario (aunque Drizzle lo hace por $defaultFn)
            const [newUser] = await tx.insert(users)
              .values({
                email: user.email,
                passwordHash: user.passwordHash,
                firstName: user.firstName,
                lastName: user.lastName,
                phone: user.phone,
                isVerified: user.isVerified
                // Note: UUID/ULID is generated by default on schema definition
              })
              .returning()
            if (newUser == null) throw new Error('Failed to create user')
            savedUser = newUser

            // 1.1. Account creation temporarily disabled - handled by registration strategy
            // const [newAccount] = await tx.insert(accounts)
            //   .values({
            //     accountName: `${savedUser.firstName} ${savedUser.lastName} Account`,
            //     type: 'INDIVIDUAL'
            //   })
            //   .returning()
            // if (newAccount == null) throw new Error('Failed to create account')

            // 1.2. Link User with Account (disabled)
            // await tx.insert(accountUsers).values({
            //   accountId: newAccount.id,
            //   userId: savedUser.id,
            //   permissionLevel: 'OWNER'
            // })
          } else {
            // Actualizar usuario existente
            const [updatedUser] = await tx.update(users)
              .set({
                email: user.email,
                passwordHash: user.passwordHash,
                firstName: user.firstName,
                lastName: user.lastName,
                phone: user.phone,
                isVerified: user.isVerified,
                updatedAt: new Date()
              })
              .where(eq(users.id, user.id))
              .returning()

            if (updatedUser == null) throw new UserNotFoundError(`User with ID ${user.id} not found for update`)
            savedUser = updatedUser

            // 2. Sincronizar Roles (Borrar y Reinsertar)
            await tx.delete(userRoles).where(eq(userRoles.userId, savedUser.id))
          }

          // 3. Insertar roles (tanto para nuevo como para update)
          if (user.roles.length > 0) {
            const roleInserts = user.roles.map(role => ({
              userId: savedUser.id,
              role
            }))
            await tx.insert(userRoles).values(roleInserts)
          }

          // 4. Retornar el User de Dominio completo (reconstruido)
          return this.mapToDomain({
            ...savedUser,
            roles: user.roles
          })
        })
      },
      retryConfig,
      isSerializationError
    )
  }

  /**
   * {@inheritDoc}
   */
  public async findByEmail (email: string): Promise<User | null> {
    const dbUser = await this.getUserWithRoles(email)
    return (dbUser != null) ? this.mapToDomain(dbUser) : null
  }

  /**
   * {@inheritDoc}
   */
  public async findById (id: string): Promise<User | null> {
    const dbUser = await this.getUserWithRoles(id)
    return (dbUser != null) ? this.mapToDomain(dbUser) : null
  }

  /**
   * Función para obtener el usuario y sus roles de forma eficiente.
   */
  private async getUserWithRoles (identifier: string): Promise<(typeof users.$inferSelect & { roles: string[] }) | undefined> {
    console.log('[DrizzleUserAdapter] getUserWithRoles called with:', identifier)

    // Check if it looks like an email (contains @)
    const isEmail = identifier.includes('@')

    let dbUser
    if (isEmail) {
      console.log('[DrizzleUserAdapter] Searching by email:', identifier.toLowerCase())
      const [user] = await this.db.select().from(users).where(eq(users.email, identifier.toLowerCase())).limit(1)
      dbUser = user
    } else {
      // Search by ID
      console.log('[DrizzleUserAdapter] Searching by ID:', identifier)
      const [user] = await this.db.select().from(users).where(eq(users.id, identifier)).limit(1)
      dbUser = user
    }

    console.log('[DrizzleUserAdapter] DB User found:', dbUser?.email)

    if (dbUser == null) return undefined

    // 2. Obtener roles asociados
    const userRolesResult = await this.db.select({ role: userRoles.role })
      .from(userRoles)
      .where(eq(userRoles.userId, dbUser.id))

    // 3. Combinar y retornar
    const roles = userRolesResult.map(r => r.role)

    return {
      ...dbUser,
      roles
    }
  }

  /**
   * {@inheritDoc}
   */
  public async existsByEmail (email: string): Promise<boolean> {
    const result = await this.db.select({ count: users.id })
      .from(users)
      .where(eq(users.email, email.toLowerCase()))
      .limit(1)

    return result.length > 0
  }

  /**
   * {@inheritDoc}
   */
  public async deleteById (id: string): Promise<void> {
    await this.db.delete(users).where(eq(users.id, id))
    // Drizzle se encarga de las eliminaciones en cascada para userRoles y accountUsers
  }

  /**
   * Get all users with their roles
   */
  public async findAll (): Promise<User[]> {
    const allUsers = await this.db.select().from(users)

    const usersWithRoles = await Promise.all(
      allUsers.map(async (user) => {
        const userRolesResult = await this.db.select({ role: userRoles.role })
          .from(userRoles)
          .where(eq(userRoles.userId, user.id))

        return {
          ...user,
          roles: userRolesResult.map(r => r.role)
        }
      })
    )

    return usersWithRoles.map(u => this.mapToDomain(u))
  }

  /**
   * Acquire a PostgreSQL advisory lock.
   * @param {number} lockKey - The lock key (must be a 64-bit integer).
   * @param {number} timeoutMs - Timeout in milliseconds.
   * @returns {Promise<boolean>} True if lock acquired, false otherwise.
   */
  public async acquireLock (lockKey: number, timeoutMs: number): Promise<boolean> {
    try {
      // Set statement timeout to prevent indefinite blocking
      await this.db.execute(sql`SET LOCAL statement_timeout = ${timeoutMs}`)

      // Try to acquire the lock (blocking call)
      const result = await this.db.execute(
        sql`SELECT pg_advisory_lock(${lockKey})`
      )

      return result != null
    } catch (error: any) {
      // Lock timeout error code 57014
      if (error.code === '57014') {
        return false
      }
      throw error
    }
  }

  /**
   * Release a PostgreSQL advisory lock.
   * @param {number} lockKey - The lock key to release.
   */
  public async releaseLock (lockKey: number): Promise<void> {
    try {
      await this.db.execute(
        sql`SELECT pg_advisory_unlock(${lockKey})`
      )
    } catch (error) {
      // Log but don't throw - lock release failures are not critical
      console.warn('Failed to release advisory lock', { lockKey, error })
    }
  }
}
