// src/infrastructure/database/repositories/DrizzleUserAdapter.ts

import { inject } from 'tsyringe'
import { type DbClient } from '../drizzle/client'
import { accountUsers, accounts, roleEnum, userRoles, users } from '../drizzle/schema'

import { IUserRepository } from '../../../domain/repositories/IUserRepository'
import { User } from '../../../domain/entities/User'
import { UserNotFoundError } from '../../../domain/errors/DomainError'
import { eq } from 'drizzle-orm'
import { injectable, singleton } from 'tsyringe'
import { INJECTION_TOKENS } from '../../DI/InjectionTokens'

/**
 * @class DrizzleUserAdapter
 * @description Adaptador que implementa el contrato IUserRepository (Port)
 * utilizando Drizzle ORM y PostgreSQL (Adapter).
 * Es responsable de mapear Entidades de Dominio a DTOs de Drizzle y viceversa.
 * @author Petpay Architecture Team
 * @version 1.0
 */
@injectable()
@singleton()
export class DrizzleUserAdapter implements IUserRepository {
  private readonly db: DbClient

  /**
   * @constructor
   * @param {DbClient} db - Cliente Drizzle inyectado por el contenedor DI.
   */
  constructor (@inject(INJECTION_TOKENS.DB_CLIENT) db: DbClient) {
    this.db = db
  }

  // --- Mappers ---

  /**
   * @private
   * Mapea un resultado de consulta de Drizzle a la Entidad de Dominio User.
   */
  private mapToDomain (dbUser: typeof users.$inferSelect & { roles: string[] }): User {
    if (!dbUser.id) {
      throw new Error('User fetched from DB must have an ID')
    }

    // Convertir el ID de string (DB) a number (Entidad User, si se hubiera usado number)
    // Usamos el ID de tipo string (varchar(36)) tal como está definido en el esquema.

    return new User({
      id: dbUser.id,
      email: dbUser.email,
      passwordHash: dbUser.passwordHash,
      firstName: dbUser.firstName,
      lastName: dbUser.lastName,
      phone: dbUser.phone ?? undefined,
      roles: dbUser.roles as any, // Cast a Role[]
      isVerified: dbUser.isVerified,
      createdAt: dbUser.createdAt,
      updatedAt: dbUser.updatedAt
    })
  }

  // --- Implementación IUserRepository ---

  /**
   * {@inheritDoc}
   * Implementa la lógica de persistencia transaccional del Aggregate Root User.
   * * Importante: La lógica de creación de Account para un nuevo usuario ocurre aquí
   * * como parte del Aggregate Root o se delega a la capa de Aplicación.
   */
  public async save (user: User): Promise<User> {
    const isNewUser = !user.id

    return await this.db.transaction(async (tx) => {
      let savedUser: typeof users.$inferSelect

      // 1. Insertar o Actualizar la tabla principal de usuarios
      if (isNewUser) {
        // Generamos el ID si es un nuevo usuario (aunque Drizzle lo hace por $defaultFn)
        const [newUser] = await tx.insert(users)
          .values({
            email: user.email,
            passwordHash: user.passwordHash,
            firstName: user.firstName,
            lastName: user.lastName,
            phone: user.phone,
            isVerified: user.isVerified
            // Note: UUID/ULID is generated by default on schema definition
          })
          .returning()
        if (newUser == null) throw new Error('Failed to create user')
        savedUser = newUser

        // 1.1. Account creation temporarily disabled - handled by registration strategy
        // const [newAccount] = await tx.insert(accounts)
        //   .values({
        //     accountName: `${savedUser.firstName} ${savedUser.lastName} Account`,
        //     type: 'INDIVIDUAL'
        //   })
        //   .returning()
        // if (newAccount == null) throw new Error('Failed to create account')

        // 1.2. Link User with Account (disabled)
        // await tx.insert(accountUsers).values({
        //   accountId: newAccount.id,
        //   userId: savedUser.id,
        //   permissionLevel: 'OWNER'
        // })
      } else {
        // Actualizar usuario existente
        const [updatedUser] = await tx.update(users)
          .set({
            email: user.email,
            passwordHash: user.passwordHash,
            firstName: user.firstName,
            lastName: user.lastName,
            phone: user.phone,
            isVerified: user.isVerified,
            updatedAt: new Date()
          })
          .where(eq(users.id, user.id))
          .returning()

        if (updatedUser == null) throw new UserNotFoundError(`User with ID ${user.id} not found for update`)
        savedUser = updatedUser

        // 2. Sincronizar Roles (Borrar y Reinsertar)
        await tx.delete(userRoles).where(eq(userRoles.userId, savedUser.id))
      }

      // 3. Insertar roles (tanto para nuevo como para update)
      if (user.roles.length > 0) {
        const roleInserts = user.roles.map(role => ({
          userId: savedUser.id,
          role
        }))
        await tx.insert(userRoles).values(roleInserts)
      }

      // 4. Retornar el User de Dominio completo (reconstruido)
      return this.mapToDomain({
        ...savedUser,
        roles: user.roles
      })
    })
  }

  /**
   * {@inheritDoc}
   */
  public async findByEmail (email: string): Promise<User | null> {
    const dbUser = await this.getUserWithRoles(email)
    return (dbUser != null) ? this.mapToDomain(dbUser) : null
  }

  /**
   * {@inheritDoc}
   */
  public async findById (id: string): Promise<User | null> {
    const dbUser = await this.getUserWithRoles(id)
    return (dbUser != null) ? this.mapToDomain(dbUser) : null
  }

  /**
   * Función para obtener el usuario y sus roles de forma eficiente.
   */
  private async getUserWithRoles (identifier: string): Promise<(typeof users.$inferSelect & { roles: string[] }) | undefined> {
    console.log('[DrizzleUserAdapter] getUserWithRoles called with:', identifier)
    
    // Check if it looks like an email (contains @)
    const isEmail = identifier.includes('@')
    
    let dbUser
    if (isEmail) {
      console.log('[DrizzleUserAdapter] Searching by email:', identifier.toLowerCase())
      const [user] = await this.db.select().from(users).where(eq(users.email, identifier.toLowerCase())).limit(1)
      dbUser = user
    } else {
      // Search by ID
      console.log('[DrizzleUserAdapter] Searching by ID:', identifier)
      const [user] = await this.db.select().from(users).where(eq(users.id, identifier)).limit(1)
      dbUser = user
    }

    console.log('[DrizzleUserAdapter] DB User found:', dbUser?.email)

    if (dbUser == null) return undefined

    // 2. Obtener roles asociados
    const userRolesResult = await this.db.select({ role: userRoles.role })
      .from(userRoles)
      .where(eq(userRoles.userId, dbUser.id))

    // 3. Combinar y retornar
    const roles = userRolesResult.map(r => r.role)

    return {
      ...dbUser,
      roles
    }
  }

  /**
   * {@inheritDoc}
   */
  public async existsByEmail (email: string): Promise<boolean> {
    const result = await this.db.select({ count: users.id })
      .from(users)
      .where(eq(users.email, email.toLowerCase()))
      .limit(1)

    return result.length > 0
  }

  /**
   * {@inheritDoc}
   */
  public async deleteById (id: string): Promise<void> {
    await this.db.delete(users).where(eq(users.id, id))
    // Drizzle se encarga de las eliminaciones en cascada para userRoles y accountUsers
  }

  /**
   * Get all users with their roles
   */
  public async findAll (): Promise<User[]> {
    const allUsers = await this.db.select().from(users)
    
    const usersWithRoles = await Promise.all(
      allUsers.map(async (user) => {
        const userRolesResult = await this.db.select({ role: userRoles.role })
          .from(userRoles)
          .where(eq(userRoles.userId, user.id))
        
        return {
          ...user,
          roles: userRolesResult.map(r => r.role)
        }
      })
    )
    
    return usersWithRoles.map(u => this.mapToDomain(u))
  }
}
