services:
  auth-app:
    build: .
    container_name: auth-microservice-app
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@auth-db:5432/${DB_NAME}
      EMAIL_SERVICE: gmail
      EMAIL_USER: dojoshinkannidan@gmail.com
      EMAIL_PASSWORD: "kprq baud engu loqo"
      JWT_SECRET: ${JWT_SECRET_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL}
      OAUTH_STATE_SECRET: ${OAUTH_STATE_SECRET}
      REDIS_URL: redis://redis:6379
    depends_on:
      - auth-db
      - redis
    networks:
      - auth-net
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: bun.lockb
    command: bun run dev

  auth-db:
    image: postgres:alpine3.22
    container_name: auth-microservice-db

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - auth-net

  redis:
    image: redis:7-alpine
    container_name: auth-microservice-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-net
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  auth-net:
