name: Lint Code

on:
  pull_request:
    branches: [main, develop]
    paths: ['Identity/**']
  push:
    branches: [main, develop]
    paths: ['Identity/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5.0.0
      
      - uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: ./Identity
        
      - name: Run linter
        run: bun run lint:fix
        working-directory: ./Identity